paketApp2/webdata/api/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from webdata.models import Package, Api, User
from webdata import db, bcrypt, mail, app
from flask_login import login_required, current_user, login_user, logout_user
import requests
from flask_cors import CORS, cross_origin
from datetime import datetime
from pytz import timezone
api = Blueprint('api', __name__)


CORS = CORS(app, supports_credentials=True)
#POST METHOD
@api.route('/add/<awb>/<expedition>/<owner>')
@login_required
def add(awb, expedition, owner):
    newPaket = Packages(awb=awb, expedition=expedition, owner=owner)
    db.session.add(newPaket)
    db.session.commit()
    return "Paket added"

@api.route('/addreceiver/<int:id>/<int:user_id>')
@login_required
def addreceiver(id, user_id):
    paket = Packages.query.get(id)
    paket.receiver_id = user_id
    db.session.commit()
    return "Receiver added"

@api.route('/packagedata/<int:id>/awb')
def getdata(id, awb):
    api = Packages.query.get(id)
    r = requests.get(f'https://api.binderbyte.com/v1/track?api_key={api.api}&courier={api.expedition}&awb={awb}')
    r_dict = r.json()
    if r.status_code == 200:
        return r_dict['data']['summary']['awb'], r_dict['data']['detail']['receiver'], r_dict['data']['summary']['courier']
    else :
        return "Error"

@api.route('/get_package_json/')
@api.route('/get_package_json/<pin>')
@cross_origin(supports_credentials=True)
def get_package_json_pin(pin =''):
    tem = datetime.now(timezone('Asia/Jakarta')).date().strftime('%Y-%m-%d')
    if pin != None and pin != '' and pin != 'undefined' and pin != 'null': 
        # Format time to Asia/Jakarta now, yyyy-mm-dd
        # packages = Package.query.filter(Package.owner.like(f'%{pin}%')).all()
        packages = Package.query.filter(Package.owner.like(f'%{pin}%')).filter(Package.date_created.like(f'%{tem}%')).all()
        # Get packages data where date is today
        # packages_today = Package.query.filter(Package.owner.like(f'%{pin}%')).filter(Package.date.like(f'%{datetime.now().strftime("%Y-%m-%d")}%')).all()
        if packages :
            the_json = []
            for package in packages:
                the_json.append({
                    'id': package.id,
                    'awb': package.awb,
                    'expedition' : package.expedition,
                    'owner': package.owner,
                    'receiver_id': package.receiver_id,
                })
            the_json = sorted(the_json, key=lambda k: k['owner'], reverse=False)
            return jsonify(the_json)
        
        packages = Package.query.filter(Package.awb.like(f'%{pin}%')).filter(Package.date_created.like(f'%{tem}%')).all()
        if packages :
            the_json = []
            for package in packages:
                the_json.append({
                    'id': package.id,
                    'awb': package.awb,
                    'expedition' : package.expedition,
                    'owner': package.owner,
                    'receiver_id': package.receiver_id,
                })
            # Sort by owner 
            the_json = sorted(the_json, key=lambda k: k['owner'], reverse=False)
            return jsonify(the_json)
        
        packages = Package.query.filter(Package.expedition.like(f'%{pin}%')).filter(Package.date_created.like(f'%{tem}%')).all()
        if packages:
            the_json = []
            for package in packages:
                temp = package.user.first_name
                the_json.append({
                    'id': package.id,
                    'awb': package.awb,
                    'expedition' : package.expedition,
                    'owner': package.owner,
                    'receiver_id': package.receiver_id,
                })
            the_json = sorted(the_json, key=lambda k: k['owner'], reverse=False)
            return jsonify(the_json)
    else :
        packages = Package.query.filter(Package.date_created.like(f'%{tem}%')).all()
        the_json = []
        for package in packages:
            the_json.append({
                'id': package.id,
                'awb': package.awb,
                'expedition' : package.expedition,
                'owner': package.owner,
                'receiver_id': package.receiver_id,
            })
        the_json = sorted(the_json, key=lambda k: k['owner'], reverse=False)
        return jsonify(the_json)

paketApp2/webdata/main/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from flask_login import login_user, current_user, logout_user, login_required, current_user
from webdata.models import User, Package, Api
from webdata.main.forms import LoginForm, RequestResetForm, ResetPasswordForm
from webdata import db, bcrypt, mail, app
from flask_mail import Message
main = Blueprint('main', __name__)

@main.route('/')
@login_required
def index():
    if current_user.user_type == 0:
        return redirect(url_for('admin.index'))
    if current_user.user_type == 1:
        return redirect(url_for('user.index'))
    return render_template('index.html')

@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
            return redirect(url_for('main.login'))
    return render_template('login.html', form=form)
    
@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('main.index'))

@main.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('main.login'))
    return render_template('reset_password.html', form=form)   


@main.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('main.reset_password'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        if form.password.data != form.confirm_password.data:
            flash('Passwords do not match', 'danger')
            print(jalan)
            return redirect(url_for('main.reset_token', token=token))
        else : 
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user.password = hashed_password
            db.session.commit()
            flash('Your password has been updated! You are now able to log in', 'success')
            return redirect(url_for('main.login'))
    return render_template('reset_token.html', form=form)

@main.route('/get_package_json')
def get_package_json():
    packages = Package.query.all()
    the_json = []
    for package in packages:
        the_json.append({
            'id': package.id,
            'awb': package.awb,
            'expedition' : package.expedition,
            'owner': package.owner,
            'receiver_id': package.receiver_id,
        })
    return jsonify(the_json)


def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request',
                  sender=f"{app.config['MAIL_USERNAME']}",
                  recipients=[user.email])
    msg.body = f'''To reset your password, visit the following link:
{url_for('main.reset_token', token=token, _external=True)}

If you did not make this request then simply ignore this email and no changes will be made.
'''
    mail.send(msg)

paketApp2/webdata/user/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from webdata.models import User, Package, Api
from datetime import datetime
from pytz import timezone
from webdata import db, bcrypt, mail
from flask_login import login_user, current_user, logout_user, login_required
user = Blueprint('user', __name__)

@user.route('/')
@login_required
def index():
    # Get all packages for the date today
    # packages = Package.query.filter_by(date_created=datetime.now(timezone('Asia/Jakarta')).date()).all()
    
    # Get latest two packages
    packages = Package.query.order_by(Package.date_created.desc()).limit(2).all()
    print(packages)
    return render_template('user/index.html', packages=packages)

@user.route('/smp')
@login_required
def smp():
    return render_template('user/smp.html')

@user.route('/claim/<int:id>')
@login_required
def claim(id):
    package = Package.query.get_or_404(id)
    if package.receiver_id:
        flash('Packages has been claimed', 'warning')
        return redirect(url_for('user.index'))
    package.receiver_id = current_user.id
    db.session.commit()
    flash(f'Package {package.awb} been claimed!', 'info')
    return redirect(url_for('user.index'))

@user.route('/unclaim/<int:id>')
@login_required
def unclaim(id):
    package = Package.query.get(id)
    if current_user.id != package.receiver_id and current_user.user_type != 0:
        flash('You are not the owner of this package!', 'danger')
        return redirect(url_for('main.index'))
    package.receiver_id = None
    db.session.commit()
    flash(f'Package {package.awb} has been unclaimed!', 'info')
    return redirect(url_for('user.index'))
@user.route('/claim2/<int:id>')
@login_required
def claim2(id):
    package = Package.query.get_or_404(id)
    if package.receiver_id:
        flash('Packages has been claimed', 'warning')
        return redirect(url_for('user.packages'))
    package.receiver_id = current_user.id
    db.session.commit()
    flash(f'Package {package.awb} been claimed!', 'info')
    return redirect(url_for('user.packages'))

@user.route('/unclaim2/<int:id>')
@login_required
def unclaim2(id):
    package = Package.query.get(id)
    if current_user.id != package.receiver_id and current_user.user_type != 0:
        flash('You are not the owner of this package!', 'danger')
        return redirect(url_for('user.packages'))
    package.receiver_id = None
    db.session.commit()
    flash(f'Package {package.awb} has been unclaimed!', 'info')
    return redirect(url_for('user.packages'))

@user.route('/packages')
@login_required
def packages():
    tem = datetime.now(timezone('Asia/Jakarta')).date().strftime("%Y-%m-%d")
    packages = Package.query.filter(Package.date_created.like(f'%{tem}%')).all()
    # print("jalan")
    return render_template('user/packages.html', packages=packages)

paketApp2/webdata/templates/user/index.html
{% extends 'user/layout.html'%}
{% block content %}DASHBOARD{% endblock content %}

{% block body %}
<div class="section full mt-2">
    <!-- <div class="section-title">Profile</div> -->
    <div class="wide-block pt-2 pb-2 mt-3">
        <div class="card mb-3" style="max-width: 100vw;">
            <div class="row g-0">
              <div class="col-md-4 text-center">
                <img src="/static/img/undraw_profile.svg" style="width : 70%; height : 70%;" class="img-fluid rounded-circle" alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">Profile</h5>
                  <p class="card-text">
                    <ul>
                        <li>Name : {{current_user.first_name.title()}} {{current_user.last_name.title()}}</li>
                        <li>Room : {{current_user.room}}</li>
                        <li>Register : {{current_user.date_created.strftime('%Y-%m-%d')}}</li>
                        <li>Package Claimed : {{current_user.package_claimed | length}}</li>
                    </ul>
                  </p>
                  <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
                </div>
              </div>
            </div>
          </div>    
    </div>
</div> 
<div class="section full mt-2">
    <div class="section-title">Recent Packages</div>
    <div class="wide-block pt-2 pb-2">
        <div class="row">
            <div class="col-4">
                <span>Latest</span>
            </div>
            <div class="col-4"></div>
            <div class="col-4 text-right">
                <a href="{{url_for('user.packages')}}">
                    <span class="">View All</span>
                </a>
            </div>
        </div>
        <hr>
        <!-- loop produk -->

        {% if packages %}
        {% for package in packages %}
        <div class="section mt-3 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-subtitle"></h6>
                            <h5 class="card-title">{{ package.owner }}</h5>
                            <p class="card-text">
                                {{package.expedition}} : {{ package.awb }}
                            </p>
                            <p class="card-text">{{package.date_created}}</p>
                            {% if package.receiver_id == None %}
                                <a href="/user/claim/{{package.id}}" class="btn btn-primary">
                                    <ion-icon name="cube-outline" role="img" class="md hydrated" aria-label="cube outline"></ion-icon>
                                    Claim
                                </a>
                            {% else %}
                                {% if current_user.id == package.receiver_id %}
                                    <a href="/user/unclaim/{{package.id}}" class="btn btn-danger">
                                        <ion-icon name="cube-outline" role="img" class="md hydrated" aria-label="cube outline"></ion-icon>
                                        Unclaim
                                    </a>
                                {% else %}
                                    <a href="#" class="btn btn-info">
                                        <ion-icon name="cube-outline" role="img" class="md hydrated" aria-label="cube outline"></ion-icon>
                                        Claimed
                                    </a>   
                                    <span class="card-text">
                                        {{package.user.first_name[0:10]}}               
                                    </span>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
        {% endfor %}
        {% else %}
        <div class="section mt-3 mb-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-subtitle"></h6>
                    <h5 class="card-title">PAKET</h5>
                    <p class="card-text">
                        Reusable components designed for the mobile interface and ready to use.
                    </p>
                    <a href="app-components.html" class="btn btn-primary">
                        <ion-icon name="cube-outline" role="img" class="md hydrated" aria-label="cube outline"></ion-icon>
                        Preview
                    </a>
                </div>
            </div>
        </div>a
        {% endif %}

        
    </div>
</div>

{% endblock body %}

paketApp2/webdata/templates/user/layout.html
<!doctype html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#000000">
    <title>Package</title>
    <meta name="description" content="Lagustinus211">
    <meta name="keywords">
    <link rel="icon" type="image/png" href="/static/assets/img/favicon.png" sizes="32x32">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/assets/img/icon/192x192.png">
    <link rel="stylesheet" href="/static/assets/css/style.css">
    <link rel="manifest" href="__manifest.json">
</head>

<body>

    <!-- loader -->
    <div id="loader">
        <div class="spinner-border text-primary" role="status"></div>
    </div>
    <!-- * loader -->

    <!-- App Header -->
    <div class="appHeader bg-light text-primary">
        <div class="left">
            <a href="javascript:;" class="headerButton goBack">
                <ion-icon name="chevron-back-outline"></ion-icon>
            </a>
        </div>
        <div class="pageTitle">{% block content %}{% endblock content%}</div>
        <div class="right"></div>
    </div>
    <!-- * App Header -->

    <!-- App Capsule -->
    <div id="appCapsule">
        <div class="row">
            <div class="col-1"></div>
            <div class="col-10 text-center mt-2">
              {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
              {% endwith %}
            </div>
          </div>
        {% block body %}
        {% endblock body %}
    </div>
    <!-- * App Capsule -->

    <!-- App Bottom Menu -->
    <div class="appBottomMenu">
        
        <a href="{{url_for('user.index')}}" class="item">
            <div class="col">
                <ion-icon name="home-outline"></ion-icon>
            </div>
        </a>
        <a href="{{url_for('user.packages')}}" class="item">
            <div class="col">
                <ion-icon name="albums-outline"></ion-icon>
            </div>
        </a>
        <a href="#" class="item">
            <div class="col">
                <ion-icon name="camera-outline"></ion-icon>
            </div>
        </a>
        <a href="#" class="item">
            <div class="col">
                <ion-icon name="settings-outline"></ion-icon>
            </div>
        </a>
        <!-- a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal" -->
        <a href="#" class="item" data-toggle="modal" data-target="#logoutModal">
            <div class="col">
                <ion-icon name="exit-outline"></ion-icon>
            </div>
        </a>

    </div>
    <!-- * App Bottom Menu -->

    <!-- ///////////// Js Files ////////////////////  -->
    <!-- Jquery -->
    <script src="/static/assets/js/lib/jquery-3.4.1.min.js"></script>
    <!-- Bootstrap-->
    <script src="/static/assets/js/lib/popper.min.js"></script>
    <script src="/static/assets/js/lib/bootstrap.min.js"></script>
    <!-- Ionicons -->
    <script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.js"></script>
    <!-- Owl Carousel -->
    <script src="/static/assets/js/plugins/owl-carousel/owl.carousel.min.js"></script>
    <!-- jQuery Circle Progress -->
    <script src="/static/assets/js/plugins/jquery-circle-progress/circle-progress.min.js"></script>
    <!-- Base Js File -->
    <script src="/static/assets/js/base.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.1.3/axios.min.js"></script>
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{{url_for('main.logout')}}">Logout</a>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

paketApp2/webdata/templates/user/packages.html
{% extends 'user/layout.html' %}
{% block content %}PACKAGES{% endblock content %}
{% block body %}
    <div class="section full mt-2 container">
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <h2 class="text-center col-12">
                        Tanggal
                    </h2>
                    <input type="date" name="" id="" class="ml-2 mr-2 form form-control" value="2022-07-22" disabled>
                </div>
            </div>
            <div class="col-12">
                <div class="row">
                    <h2 class="text-center col-12">
                        Cari
                    </h2>
                    <input type="text" autofocus oninput="feeddata()" id="inp" class="ml-2 mr-2 form form-control">
                </div>
            </div>
        </div>
    </div>
        <div class="section mt-2" id="tag">
            <hr>
            <!-- item -->
            {% for package in packages %}
            <div class="card cart-item mb-2">
                <div class="card-body">
                    <div class="in">
                        <div class="text">
                            <h3 class="title">{{package.owner}}</h3>
                            <p class="detail">{{package.awb}}</p>
                            <strong class="price">{{package.expedition}}</strong>
                        </div>
                    </div>
                    {% if package.receiver_id == None %}
                        <div class="cart-item-footer">
                            <a href="/user/claim2/{{package.id}}" class="ml-2 btn btn-outline-secondary btn-sm btn-secondary">Claim</a>
                        </div>
                    {% else %}
                        {% if package.receiver_id == current_user.id %}
                        <div class="cart-item-footer">
                            <a href="/user/unclaim2/{{package.id}}" class="ml-2 btn btn-outline-danger btn-sm btn-danger">Unclaim</a>
                        </div>
                        {% else %}
                        <div class="cart-item-footer">
                            <a href="#" class="ml-2 btn btn-outline-secondary btn-sm btn-secondary">Claimed</a>
                        </div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <!-- * item -->
            {% endfor %}
        </div>
    <script>
        function corta(data) {
            console.log(tag)
            var htm=''
            data.forEach(tag => {
                console.log(tag)
                var pot=""
                if(tag.receiver_id == {{current_user.id}}){
                    pot=`<div class="cart-item-footer">
                                <a href="/user/unclaim2/${tag.id}" class="ml-2 btn btn-outline-secondary btn-sm btn-danger">Unclaim</a>
                            </div>`
                }else if (tag.receiver_id!=null) {
                    pot=`<div class="cart-item-footer">
                                <a href=#" class="ml-2 btn btn-outline-info btn-sm btn-infor">Claimed</a>
                            </div>`
                }else{
                    pot=`<div class="cart-item-footer">
                                <a href="/user/claim2/${tag.id}" class="ml-2 btn btn-outline-secondary btn-sm btn-secondary">Claim</a>
                            </div>`
                }
                htm+=`
                    <div class="card cart-item mb-2">
                        <div class="card-body">
                            <div class="in">
                                <div class="text">
                                    <h3 class="title">${tag.owner}</h3>
                                    <p class="detail">${tag.awb}</p>
                                    <strong class="price">${tag.expedition}</strong>
                                </div>
                            </div>
                            ${pot}
                        </div>
                    </div>
                    `
            });
            document.getElementById("tag").innerHTML=htm
        }

        function feeddata(pin){
            if (p=='') {
                p=''
            }
            var requestOptions = {
                method: 'GET',
                redirect: 'follow'
            };
            var p=document.getElementById("inp").value;
            fetch("{{url_for('api.get_package_json_pin')}}"+p, requestOptions)
            .then(response => response.json())
            .then(
                result => corta(result)
                )
            .catch(error => console.log('error', error));
        }
        feeddata()

    </script>
    {% endblock body %}

paketApp2/webdata/templates/user/sss.html
<div class="container">
    <div class="col">
        <div class="row">
                <div class="col-md-12 mt-3">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                          {% if messages %}
                            {% for category, message in messages %}
                              <div class="alert alert-{{ category }}">
                                {{ message }}
                              </div>
                            {% endfor %}
                          {% endif %}
                        {% endwith %}
                        <div class="text-end"> 
                            <a href="{{url_for('main.logout')}}" class="btn btn-warning mb-2 me-md-2">Logout</a>
                        </div>
                </div>
        </div>
        <div class="row">
            {% for package in packages %}
            <div class="col-md-4 mt-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{package.owner}}</h5>
                        <p class="card-text">{{package.awb}}</p>
                        {% if current_user.user_type == 0 %}
                            {% if package.receiver_id %}
                                 <a href="/user/unclaim/{{package.id}}" class="btn btn-danger">Unclaim</a>
                            {% else %}
                                <a href="/user/claim/{{package.id}}" class="btn btn-primary">Claim</a>
                            {% endif %}
                        {% else %}
                            {% if package.receiver_id %}
                                {% if package.receiver_id == current_user.id %}
                                    <a href="/user/unclaim/{{package.id}}" class="btn btn-danger">Unclaim</a>
                                {% else %}

                                    <a href="#" class="btn btn-info" disabled>Claimed</a>
                                {% endif %}
                            {% else %}
                                <a href="/user/claim/{{package.id}}" class="btn btn-primary">Claim</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>